# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConclusionPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_id', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('study', models.CharField(max_length=500)),
                ('blocks', jsonfield.fields.JSONField()),
            ],
        ),
    ]
