# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digestif', '0003_conclusionpage_path_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(max_length=100)),
                ('path_name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('benefits', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='conclusionpage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='conclusionpage',
            name='path_names',
        ),
        migrations.AddField(
            model_name='conclusionpage',
            name='full_page',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conclusionpage',
            name='cp_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='conclusionpage',
            name='blocks',
            field=models.ManyToManyField(to='digestif.Block'),
        ),
    ]
